config/routes.rb
Rails.application.routes.draw do
resources :users
resource :session
resources :subs
resources :posts do
  get '/comments/new' => 'comments#new'
  get '/upvote/' => 'posts#upvote'
  get '/downvote/' => 'posts#downvote'
end
resources :comments, :only => [:create, :edit, :update, :destroy, :show] do
  get '/comments/new' => 'comments#new_child'
  get '/upvote/' => 'comments#upvote'
  get '/downvote/' => 'comments#downvote'
end

end

app/models/comment.rb
class Comment<ActiveRecord::Base

  validates :commenter_id, :content, :post_id, presence: true

  belongs_to(
    :post,
    :class_name => "Post",
    foreign_key: :post_id,
    primary_key: :id
  )

  belongs_to(:parent,
    :class_name => "Comment",
    :foreign_key => :parent_comment_id,
    :primary_key => :id
  )

  belongs_to(:commenter,
      :class_name => "User",
      :foreign_key => :commenter_id,
      :primary_key => :id
  )

  has_many(:comments,
  :class_name => "Comment",
  :foreign_key => :parent_comment_id,
  :primary_key => :id
)

  has_many :votes, as: :votable

  def score
    self.votes.sum(:value)
  end

  def hotness
    total = 0
    self.votes.each do |vote|
      if vote.created_at > 5.minutes.ago
        vote.value *= 5
      elsif vote.created_at > 30.minutes.ago
        vote.value *= 2
      end
    total += vote.value
    end
    total
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :is_commenter?, only: [:edit, :update]

  def upvote
    user = current_user
    if user
      @vote = Vote.new
      @vote.value = 1
      @vote.voter_id = user.id
      @vote.votable_id = params[:comment_id]
      @vote.votable_type = "Comment"
      if @vote.save
        redirect_to comment_url(params[:comment_id])
      else
        redirect_to subs_url
      end
    else
      redirect_to new_session_url
    end
  end

  def downvote
    user = current_user
    if user
      @vote = Vote.new
      @vote.value = -1
      @vote.voter_id = user.id
      @vote.votable_id = params[:comment_id]
      @vote.votable_type = "Comment"
      if @vote.save
        redirect_to comment_url(params[:comment_id])
      else
        redirect_to subs_url
      end
    else
      redirect_to new_session_url
    end
  end

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    render :new

  end

  def new_child
    @comment = Comment.new
    @parent = Comment.find(params[:comment_id])
    @post = Post.find(@parent.post_id)
    render :new
  end

  def show
    @comment = Comment.find(params[:id])

    render :show
  end

  def create
    user = current_user
    if user
      @comment = Comment.new(comment_params)


      @comment.commenter_id = user.id
      if @comment.save
        redirect_to post_url(params[:comment][:post_id])
      else
        render :new
      end
    else
      redirect_to new_session_url
    end

  end

  def edit
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
    render :edit
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to comment_url(@comment)
    else
      render :edit
    end
  end

  def destroy

  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end

  def is_commenter?
    current_user.id == Comment.find(params[:id]).commenter_id
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h1> EDIT COMMENT </h1>

<form action="<%=comment_url(@comment)%>" method="POST">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">

  <input type="hidden" name="comment[parent_comment_id]" value="<%= @comment.parent_comment_id %>">


<label> content
<textarea name="comment[content]"><%= @comment.content %></textarea>
</label>
<br>



<input type="submit" value="EDIT COMMENT!">

</form>

app/views/comments/new.html.erb
<h1> CREATE COMMENT </h1>

<form action="<%=comments_url%>" method="POST">
  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
<% unless @parent.nil? %>
  <input type="hidden" name="comment[parent_comment_id]" value="<%= @parent.id %>">
  <% end %>



<label> content
<textarea name="comment[content]"><%= @comment.content %></textarea>
</label>
<br>



<input type="submit" value="CREATE COMMENT!">

</form>

app/views/comments/show.html.erb
<ul>
<li>
  <%= @comment.content %>
</li>
<li>
  <%= @comment.commenter.username %>
</li>
</ul>

<a href=" <%= comment_comments_new_url(@comment.id) %> "> reply to this comment </a>