config/routes.rb
Rails.application.routes.draw do
resources :users
resource :session
resources :subs
resources :posts do
  get '/comments/new' => 'comments#new'
  get '/upvote/' => 'posts#upvote'
  get '/downvote/' => 'posts#downvote'
end
resources :comments, :only => [:create, :edit, :update, :destroy, :show] do
  get '/comments/new' => 'comments#new_child'
  get '/upvote/' => 'comments#upvote'
  get '/downvote/' => 'comments#downvote'
end

end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, presence: true

  has_many(:post_subbings,
  class_name: "PostSubbing",
  foreign_key: :sub_id,
  primary_key: :id)

  has_many :posts, through: :post_subbings, source: :post

end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :is_mod?, :only => [:edit, :update]

  def new
    @sub = Sub.new
    render :new

  end

  def create
    user = current_user
    if user
      @sub = Sub.new(sub_params)
      @sub.moderator_id = user.id
      if @sub.save
        redirect_to sub_url(@sub)
      else
        render :new
      end
      else
        redirect_to new_session_url
      end

  end

  def index
      @subs = Sub.all
      render :index
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = @sub.posts
    render :show

  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit

  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      render :edit
    end

  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def is_mod?
    current_user.id == Sub.find(params[:id]).moderator_id
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/edit.html.erb
<h1> EDIT SUB </h1>

<form action="<%=sub_url(@sub)%>" method="POST">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
    <label> Title
  <input type="text" name="sub[title]" value="<%=@sub.title%>">
</label>
<br>

<label> description
<input type="text" name="sub[description]" value="<%=@sub.description%>">
</label>
<br>


<input type="submit" value="Edit SUB!">

</form>

app/views/subs/index.html.erb
<% @subs.each do |sub| %>
  <%= sub.title %>
<% end %>

app/views/subs/show.html.erb
<h1> <%= @sub.title %> </h1>
<ul>
  <% @posts.sort! {|c1, c2|  c2.score <=> c1.score} %>
<% @posts.each do |post| %>
  <li>
    <a href="<%= post_upvote_url(post.id) %> ">Upvote</a>
    Score: <%= post.score %>
    <a href="<%= post_downvote_url(post.id) %> ">Downvote</a>
    <% if post.url.blank? %>
      <a href="<%= post_url(post) %>"><%= post.title %></a>
      <% else %>
      <a href="<%= post.url%>"><%= post.title %></a>
    <% end %>
  </li>
<% end %>
</ul>