config/routes.rb
Rails.application.routes.draw do
resources :users
resource :session
resources :subs
resources :posts do
  get '/comments/new' => 'comments#new'
  get '/upvote/' => 'posts#upvote'
  get '/downvote/' => 'posts#downvote'
end
resources :comments, :only => [:create, :edit, :update, :destroy, :show] do
  get '/comments/new' => 'comments#new_child'
  get '/upvote/' => 'comments#upvote'
  get '/downvote/' => 'comments#downvote'
end

end

app/models/post.rb
class Post<ActiveRecord::Base
  validates :title, :content, :author_id, presence: true

  has_many(
    :post_subbings,
    class_name: "PostSubbing",
    foreign_key: :post_id,
    primary_key: :id
  )

  has_many(:comments,
    :class_name => "Comment",
    :foreign_key => :post_id,
    :primary_key => :id
    )

  has_many :votes, as: :votable

  def score
    self.votes.sum(:value)
  end

  def hotness
    total = 0
    self.votes.each do |vote|
      if vote.created_at > 5.minutes.ago
        vote.value *= 5
      elsif vote.created_at > 30.minutes.ago
        vote.value *= 2
      end
    total += vote.value
    end
    total
  end

    def top_level_comments
      self.comments.where(parent_comment_id: nil)
    end

    def comments_by_parent_id
      output = {}
      self.comments.each do |comment|
        if output[comment.parent_comment_id].nil?
          output[comment.parent_comment_id] = [comment]
        else
          output[comment.parent_comment_id] << comment
        end

      end
      output
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_author?, only: [:edit, :update]

  def upvote
    user = current_user
    if user
      @vote = Vote.new
      @vote.value = 1
      @vote.voter_id = user.id
      @vote.votable_id = params[:post_id]
      @vote.votable_type = "Post"
      if @vote.save
        redirect_to post_url(params[:post_id])
      else
        redirect_to subs_url
      end
    else
      redirect_to new_session_url
    end
  end

  def downvote
    user = current_user
    if user
      @vote = Vote.new
      @vote.value = -1
      @vote.voter_id = user.id
      @vote.votable_id = params[:post_id]
      @vote.votable_type = "Post"
      if @vote.save
        redirect_to post_url(params[:post_id])
      else
        redirect_to subs_url
      end
    else
      redirect_to new_session_url
    end
  end

  def show
    @post = Post.find(params[:id])
    @all_comments = @post.comments_by_parent_id
    render :show
  end

  def new
    @subs = Sub.all
    @post = Post.new
    render :new
  end

  def create
    @subs = Sub.all
    user = current_user
    if user
      @post = Post.new(post_params)
      @post.sub_id = params[:post][:sub].last
      @post.author_id = user.id
      if @post.save
        params[:post][:sub].each do |sub|
          PostSubbing.create(post_id: @post.id, sub_id: sub)
        end
        redirect_to post_url(@post)
      else
        render :new
      end
    else
      redirect_to new_session_url
    end
  end

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all
    @subbings = @post.post_subbings
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    @subs = Sub.all
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_id)
  end

  def is_author?
    current_user.id == Post.find(params[:id])
  end

end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<a href="<%= comment_upvote_url(comment.id) %> ">Upvote</a>
Score: <%= comment.score %>
<a href="<%= comment_downvote_url(comment.id) %> ">Downvote</a>

  <a href="<%= comment_url(comment) %>"> <%= comment.content %> </a>
  <%= comment.commenter.username %>

<% unless @all_comments[comment.id].nil? %>
  <% @all_comments[comment.id].sort! {|c1, c2|  c2.score <=> c1.score} %>

<% @all_comments[comment.id].each do |child| %>
  <br>
<%= render "comment", comment: child %>
  <br>
<% end %>
<% end %>

app/views/posts/edit.html.erb
<h1> EDIT POST </h1>

<form action="<%=post_url(@post)%>" method="POST">
  <input type="hidden" name="_method" value="patch">
  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
    <label> Title
  <input type="text" name="post[title]" value="<%=@post.title%>">
</label>
<br>

<label> url
<input type="text" name="post[url]" value="<%=@post.url%>">
</label>
<br>

<label> content
<textarea name="post[content]"><%= @post.content %></textarea>
</label>
<br>

<% @subs.each do |sub| %>
  <label> <%= sub.title %>
  <input type="checkbox" name="post[sub][]" value="<%= sub.id %>"<%= "checked" if @subbings.any?{|subbing| subbing.sub_id == sub.id } %> >
  </label>
<% end %>

<input type="submit" value="EDIT POST!">

</form>

app/views/posts/new.html.erb
<h1> CREATE POST </h1>

<form action="<%=posts_url%>" method="POST">
  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
    <label> Title
  <input type="text" name="post[title]" value="<%=@post.title%>">
</label>
<br>

<label> url
<input type="text" name="post[url]" value="<%=@post.url%>">
</label>
<br>

<label> content
<textarea name="post[content]"><%= @post.content %></textarea>
</label>
<br>

<% @subs.each do |sub| %>
  <label> <%= sub.title %>
  <input type="checkbox" name="post[sub][]" value="<%= sub.id %>">
  </label>
<% end %>

<input type="submit" value="CREATE POST!">

</form>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<%= @post.content %>

<ul>
  <% unless @all_comments[nil].nil? %>

    <% @all_comments[nil].each do |comment| %>
    <% @all_comments[nil].sort! {|c1, c2|  c2.score <=> c1.score} %>
    <li>
      <%= render "comment", comment: comment %>
    </li>
    <% end %>
  <% end %>
</ul>